[tool.black]
line-length = 100  # Longitud máxima de línea
target-version = ['py38', 'py39', 'py310']  # Versiones de Python soportadas
skip-string-normalization = true  # No cambiar comillas a dobles
include = '\.pyi?$'  # Incluir archivos .py y .pyi
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | _build
  | build
  | dist
)/
'''  # Excluir estos directorios
